---
version: "3"
networks:
  citadel:
    driver: bridge

services:
  app:
    container_name: citadel_app
    build: docker/app
    working_dir: /srv/app
    env_file:
      - citadel.env
    networks:
      - citadel
    volumes:
      - ".:/srv/app"
    ports:
      - "80:80"

  mysql:
      container_name: citadel_mysql
      build: docker/mysql
      env_file:
          - citadel.env
      volumes:
          # mysql
          - "./volumes/mysql:/var/lib/mysql"
      networks:
          - citadel

  phpmyadmin:
      container_name: citadel_phpmyadmin
      image: nazarpc/phpmyadmin
      environment:
          SESSION_TIMEOUT: 86400
      networks:
          - citadel
      ports:
          - "8082:80"

  wordpress:
    container_name: citadel_wordpress
    image: wordpress
    env_file:
      - citadel.env
    networks:
      - citadel
