---
version: "3"
networks:
    citadel:
        driver: bridge

services:
  app:
    container_name: citadel_app
    build: docker/app
    working_dir: /srv/app
    environment:
      NODE_ENV: ${NODE_ENV}
    env_file:
      - citadel.env
    networks:
      - citadel
    volumes:
      - ".:/srv/app"

  authentication_server:
      container_name: citadel_sso
      image: citadeltechnologies/authentication-server
      env_file:
          - citadel.env
      networks:
          - citadel

  redis:
      container_name: citadel_redis
      image: redis
      env_file:
          - citadel.env
      networks:
          - citadel

  redis_commander:
      container_name: citadel_redis_commander
      image: tenstartups/redis-commander
      command: --redis-host redis
      networks:
        - citadel
      ports:
        - "8081:8081"

  mysql:
      container_name: citadel_mysql
      build: docker/mysql
      env_file:
          - citadel.env
      volumes:
          # mysql
          - "./volumes/mysql:/var/lib/mysql"
      networks:
          - citadel

  phpmyadmin:
      container_name: citadel_phpmyadmin
      image: nazarpc/phpmyadmin
      environment:
          SESSION_TIMEOUT: 86400
      networks:
          - citadel
      ports:
          - "8082:80"

  wordpress:
    container_name: citadel_wordpress
    image: wordpress
    env_file:
      - citadel.env
    networks:
      - citadel

  nginx:
      container_name: citadel_nginx
      build: docker/nginx
      depends_on:
          - app
          - wordpress
      env_file:
          - citadel.env
      extra_hosts:
          - "local.la-citadelle.net:127.0.0.1"
          - "local-blog.la-citadelle.net:127.0.0.1"
      volumes:
          # applications
          - ".:/srv/app"
          # nginx
          - "./volumes/html:/usr/share/nginx/html"
          - "./volumes/logs/nginx:/var/log/nginx"
      networks:
          - citadel
      ports:
          - "443:443"
          - "80:80"
