---
version: '2'
services:
  app:
    container_name: citadel_app
    build: docker/app
    working_dir: /srv/app
    env_file:
      - citadel.env
    links:
      - mysql
    volumes:
      - ".:/srv/app"

  mysql:
      container_name: citadel_mysql
      build: docker/mysql
      env_file:
          - citadel.env
      volumes:
          # mysql
          - "./volumes/mysql:/var/lib/mysql"

  wordpress:
    container_name: citadel_wordpress
    image: wordpress
    env_file:
      - citadel.env
    links:
      - mysql

  nginx:
      container_name: citadel_nginx
      build: docker/nginx
      env_file:
          - citadel.env
      extra_hosts:
          - "local.la-citadelle.net:127.0.0.1"
          - "local-blog.la-citadelle.net:127.0.0.1"
      volumes:
          # applications
          - ".:/srv/app"
          # nginx
          - "./volumes/html:/usr/share/nginx/html"
          - "./volumes/logs/nginx:/var/log/nginx"
      links:
          - app
          - wordpress
      ports:
          - "443:443"
          - "80:80"
